#!/bin/bash
###########################################################################
# Repositorio: Nintendo64
# Por: Luciano's Tech (https://sites.google.com/view/lucianostech)
# License: http://creativecommons.org/licenses/by-sa/4.0/
###########################################################################
cd
mount -o remount,rw /
mount -o remount,rw /boot

RUTA="https://github.com/PIBSAS/Nintendo64/raw/master/"
mkdir ../roms/
mkdir ../roms/n64/
rm "../roms/n64/007 - The World Is Not Enough (USA).z64"
rm "../roms/n64/1080 TenEighty Snowboarding (Japan, USA) (En,Ja).z64"
rm "../roms/n64/40 Winks (Europe) (En,Es,It) (Proto) (1999-10-07).z64"
rm "../roms/n64/64 de Hakken!! Tamagotchi - Minna de Tamagotchi World (Japan).z64"
rm "../roms/n64/64 Hanafuda - Tenshi no Yakusoku (Japan).z64"
rm "../roms/n64/64 Oozumou 2 (Japan).z64"
rm "../roms/n64/64 Oozumou (Japan).z64"
rm "../roms/n64/64 Trump Collection - Alice no Wakuwaku Trump World (Japan).z64"
rm "../roms/n64/A Bug's Life (USA).z64"
rm "../roms/n64/AeroFighters Assault (USA).z64"
rm "../roms/n64/AeroGauge (USA).z64"
rm "../roms/n64/Aidyn Chronicles - The First Mage (USA) (Rev 1).z64"
rm "../roms/n64/Airboarder 64 (Europe).z64"
rm "../roms/n64/AI Shougi 3 (Japan).z64"
rm "../roms/n64/All-Star Baseball 2000 (USA).z64"
rm "../roms/n64/All-Star Baseball 2001 (USA).z64"
rm "../roms/n64/All-Star Baseball 99 (USA).z64"
rm "../roms/n64/All Star Tennis 99 (USA).z64"
rm "../roms/n64/Armorines - Project S.W.A.R.M. (USA).z64"
rm "../roms/n64/Army Men - Air Combat (USA).z64"
rm "../roms/n64/Army Men - Sarge's Heroes 2 (USA).z64"
rm "../roms/n64/Army Men - Sarge's Heroes (USA).z64"
rm "../roms/n64/Asteroids Hyper 64 (USA).z64"
rm "../roms/n64/Automobili Lamborghini (USA).z64"
rm "../roms/n64/Bakuretsu Muteki Bangaioh (Japan).z64"
rm "../roms/n64/Bakushou Jinsei 64 - Mezase! Resort Ou (Japan).z64"
rm "../roms/n64/Banjo-Kazooie (USA) (Rev 1).z64"
rm "../roms/n64/Banjo-Tooie (USA).z64"
rm "../roms/n64/Bassmasters 2000 (USA).z64"
rm "../roms/n64/Bass Rush - ECOGEAR PowerWorm Championship (Japan).z64"
rm "../roms/n64/Batman Beyond - Return of the Joker (USA).z64"
rm "../roms/n64/BattleTanx - Global Assault (USA).z64"
rm "../roms/n64/BattleTanx (USA).z64"
rm "../roms/n64/Battlezone - Rise of the Black Dogs (USA).z64"
rm "../roms/n64/Beetle Adventure Racing! (USA) (En,Fr,De).z64"
rm "../roms/n64/Big Mountain 2000 (USA).z64"
rm "../roms/n64/Bio F.R.E.A.K.S. (USA).z64"
rm "../roms/n64/Blast Corps (USA) (Rev 1).z64"
rm "../roms/n64/Blues Brothers 2000 (USA).z64"
rm "../roms/n64/Body Harvest (USA).z64"
rm "../roms/n64/Bomberman 64 Classic(Japan).z64"
rm "../roms/n64/Bomberman 64 - The Second Attack! (USA).z64"
rm "../roms/n64/Bomberman 64 (USA).z64"
rm "../roms/n64/Bomberman Hero (USA).z64"
rm "../roms/n64/Bottom of the 9th (USA).z64"
rm "../roms/n64/Brunswick Circuit Pro Bowling (USA).z64"
rm "../roms/n64/Buck Bumble (USA).z64"
rm "../roms/n64/Bust-A-Move 2 - Arcade Edition (USA).z64"
rm "../roms/n64/Bust-A-Move '99 (USA).z64"
rm "../roms/n64/California Speed (USA).z64"
rm "../roms/n64/Carmageddon 64 (USA).z64"
rm "../roms/n64/Castlevania - Legacy of Darkness (USA).z64"
rm "../roms/n64/Castlevania (USA) (Rev 2).z64"
rm "../roms/n64/Centre Court Tennis (Europe).z64"
rm "../roms/n64/Chameleon Twist 2 (USA).z64"
rm "../roms/n64/Chameleon Twist (USA) (Rev 1).z64"
rm "../roms/n64/Charlie Blast's Territory (USA).z64"
rm "../roms/n64/Chopper Attack (USA).z64"
rm "../roms/n64/Choro Q 64 2 - Hacha Mecha Grand Prix Race (Japan).z64"
rm "../roms/n64/Chou Kuukan Nighter Pro Yakyuu King 2 (Japan).z64"
rm "../roms/n64/Chou Kuukan Nighter Pro Yakyuu King (Japan).z64"
rm "../roms/n64/Clay Fighter 63 1-3 (USA).z64"
rm "../roms/n64/Clay Fighter - Sculptor's Cut (USA).z64"
rm "../roms/n64/Command & Conquer (USA).z64"
rm "../roms/n64/Conker's Bad Fur Day (USA).z64"
rm "../roms/n64/Cruis'n Exotica (USA).z64"
rm "../roms/n64/Cruis'n USA (USA) (Rev 2).z64"
rm "../roms/n64/Cruis'n World (USA).z64"
rm "../roms/n64/Custom Robo (Japan).z64"
rm "../roms/n64/Custom Robo V2 (Japan).z64"
rm "../roms/n64/CyberTiger (USA).z64"
rm "../roms/n64/Dance Dance Revolution - Disney Dancing Museum (Japan).z64"
rm "../roms/n64/Dark Rift (USA).z64"
rm "../roms/n64/Deadly Arts (USA).z64"
rm "../roms/n64/Densha de Go! 64 (Japan).z64"
rm "../roms/n64/Derby Stallion 64 (Japan).z64"
rm "../roms/n64/Destruction Derby 64 (USA).z64"
rm "../roms/n64/Dezaemon 3D (Japan).z64"
rm "../roms/n64/Diddy Kong Racing (USA) (En,Fr) (Rev 1).z64"
rm "../roms/n64/Die Hard 64 (USA) (Proto) (Level 1).z64"
rm "../roms/n64/Donald Duck - Goin' Quackers (USA) (En,Fr,De,Es,It).z64"
rm "../roms/n64/Donkey Kong 64 (USA).z64"
rm "../roms/n64/Doom 64 (USA) (Rev 1).z64"
rm "../roms/n64/Doraemon 2 - Nobita to Hikari no Shinden (Japan).z64"
rm "../roms/n64/Doraemon 3 - Nobita no Machi SOS! (Japan).z64"
rm "../roms/n64/Doraemon - Nobita to 3tsu no Seireiseki (Japan).z64"
rm "../roms/n64/Doubutsu no Mori (Japan).z64"
rm "../roms/n64/Dragon Sword 64 (USA) (Proto) (1999-08-25).z64"
rm "../roms/n64/Dr. Mario 64 (USA).z64"
rm "../roms/n64/Dual Heroes (USA).z64"
rm "../roms/n64/Duck Dodgers Starring Daffy Duck (USA) (En,Fr,Es).z64"
rm "../roms/n64/Duke Nukem 64 (USA).z64"
rm "../roms/n64/Duke Nukem - Zero Hour (USA).z64"
rm "../roms/n64/Earthworm Jim 3D (USA).z64"
rm "../roms/n64/ECW Hardcore Revolution (USA).z64"
rm "../roms/n64/Eikou no Saint Andrews (Japan).z64"
rm "../roms/n64/Excitebike 64 (USA) (Rev 1).z64"
rm "../roms/n64/Extreme-G (USA).z64"
rm "../roms/n64/Extreme-G XG2 (USA).z64"
rm "../roms/n64/F1 Pole Position 64 (USA) (En,Fr,De).z64"
rm "../roms/n64/F1 Racing Championship (Europe) (En,Fr,De,Es,It).z64"
rm "../roms/n64/F-1 World Grand Prix II (Europe) (En,Fr,De,Es).z64"
rm "../roms/n64/F-1 World Grand Prix (USA).z64"
rm "../roms/n64/Famista 64 (Japan).z64"
rm "../roms/n64/FIFA 99 (USA) (En,Fr,De,Es,It,Nl,Pt,Sv).z64"
rm "../roms/n64/FIFA - Road to World Cup 98 (USA) (En,Fr,De,Es,It,Nl,Sv).z64"
rm "../roms/n64/FIFA Soccer 64 (USA) (En,Fr,De).z64"
rm "../roms/n64/Fighter Destiny 2 (USA).z64"
rm "../roms/n64/Fighters Destiny (USA).z64"
rm "../roms/n64/Fighting Force 64 (USA).z64"
rm "../roms/n64/Flying Dragon (USA).z64"
rm "../roms/n64/Forsaken 64 (USA).z64"
rm "../roms/n64/Fox Sports College Hoops '99 (USA).z64"
rm "../roms/n64/Frogger 2 (USA) (Proto 2).z64"
rm "../roms/n64/Fushigi no Dungeon - Fuurai no Shiren 2 - Oni Shuurai! Shiren Jou! (Japan).z64"
rm "../roms/n64/F-Zero X (USA).z64"
rm "../roms/n64/gamelist.xml"
rm "../roms/n64/G.A.S.P!! Fighters' NEXTream (Japan).zip"
rm "../roms/n64/Gauntlet Legends (USA).z64"
rm "../roms/n64/Getter Love!! - Cho Renai Party Game Tanjou (Japan).z64"
rm "../roms/n64/Gex 3 - Deep Cover Gecko (USA).z64"
rm "../roms/n64/Gex 64 - Enter the Gecko (USA).z64"
rm "../roms/n64/Glover 2 (USA) (Proto 2).z64"
rm "../roms/n64/Glover (USA).z64"
rm "../roms/n64/Goemon - Mononoke Sugoroku (Japan).z64"
rm "../roms/n64/Goemon's Great Adventure (USA).z64"
rm "../roms/n64/GoldenEye 007 (USA).z64"
rm "../roms/n64/Golden Nugget 64 (USA).z64"
rm "../roms/n64/GT 64 - Championship Edition (USA).z64"
rm "../roms/n64/Hamster Monogatari 64 (Japan).z64"
rm "../roms/n64/Harukanaru Augusta - Masters '98 (Japan).z64"
rm "../roms/n64/Harvest Moon 64 (USA).z64"
rm "../roms/n64/Heiwa Pachinko World 64 (Japan).z64"
rm "../roms/n64/Hercules - The Legendary Journeys (USA).z64"
rm "../roms/n64/Hexen (USA).z64"
rm "../roms/n64/Hey You, Pikachu! (USA).z64"
rm "../roms/n64/Hot Wheels - Turbo Racing (USA).z64"
rm "../roms/n64/HSV Adventure Racing! (Australia).zip"
rm "../roms/n64/Hybrid Heaven (USA).z64"
rm "../roms/n64/Hydro Thunder (USA).z64"
rm "../roms/n64/Ide Yosuke no Mahjong Juku (Japan).z64"
rm "../roms/n64/Iggy's Reckin' Balls (USA).z64"
rm "../roms/n64/Indiana Jones and the Infernal Machine (USA).z64"
rm "../roms/n64/Indy Racing 2000 (USA).z64"
rm "../roms/n64/In-Fisherman - Bass Hunter 64 (USA).z64"
rm "../roms/n64/International Superstar Soccer 2000 (USA) (En,Es) (Rev 1).z64"
rm "../roms/n64/International Superstar Soccer 64 (USA).z64"
rm "../roms/n64/International Superstar Soccer '98 (USA).z64"
rm "../roms/n64/International Track & Field 2000 (USA).z64"
rm "../roms/n64/Itoi Shigesato no Bass Tsuri No. 1 Kettei Ban! (Japan).z64"
rm "../roms/n64/Jangou Simulation Mahjong Dou 64 (Japan).z64"
rm "../roms/n64/Jeopardy! (USA).z64"
rm "../roms/n64/Jeremy McGrath Supercross 2000 (USA).z64"
rm "../roms/n64/Jet Force Gemini (USA).z64"
rm "../roms/n64/Jikkyou G1 Stable (Japan) (Rev 1).z64"
rm "../roms/n64/Jikkyou J.League Perfect Striker (Japan).z64"
rm "../roms/n64/Jikkyou Powerful Pro Yakyuu 2000 (Japan) (Rev 1).z64"
rm "../roms/n64/Jikkyou Powerful Pro Yakyuu 4 (Japan) (Rev 1).z64"
rm "../roms/n64/Jikkyou Powerful Pro Yakyuu 5 (Japan) (Rev 2).z64"
rm "../roms/n64/Jikkyou Powerful Pro Yakyuu 6 (Japan) (Rev 2).z64"
rm "../roms/n64/Jikkyou Powerful Pro Yakyuu - Basic Ban 2001 (Japan) (Rev 1).z64"
rm "../roms/n64/Jinsei Game 64 (Japan).z64"
rm "../roms/n64/J.League Dynamite Soccer 64 (Japan).z64"
rm "../roms/n64/J.League Eleven Beat 1997 (Japan).z64"
rm "../roms/n64/J.League Live 64 (Japan).z64"
rm "../roms/n64/J.League Tactics Soccer (Japan) (Rev 1).z64"
rm "../roms/n64/John Romero's Daikatana (USA).z64"
rm "../roms/n64/Ken Griffey Jr.'s Slugfest (USA).z64"
rm "../roms/n64/Killer Instinct Gold (USA) (Rev 2).z64"
rm "../roms/n64/King Hill 64 - Extreme Snowboarding (Japan).zip"
rm "../roms/n64/Kiratto Kaiketsu! 64 Tanteidan (Japan).z64"
rm "../roms/n64/Kirby 64 - The Crystal Shards (USA).z64"
rm "../roms/n64/Knife Edge - Nose Gunner (USA).z64"
rm "../roms/n64/Knockout Kings 2000 (USA).z64"
rm "../roms/n64/Kobe Bryant in NBA Courtside (USA).z64"
rm "../roms/n64/Last Legion UX (Japan).z64"
rm "../roms/n64/LEGO Racers (USA) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).z64"
rm "../roms/n64/Lode Runner 3-D (USA).z64"
rm "../roms/n64/Mace - The Dark Age (USA).z64"
rm "../roms/n64/Madden Football 64 (USA).z64"
rm "../roms/n64/Madden NFL 2000 (USA).z64"
rm "../roms/n64/Madden NFL 2001 (USA).z64"
rm "../roms/n64/Madden NFL 2002 (USA).z64"
rm "../roms/n64/Madden NFL 99 (USA) (Rev 1).z64"
rm "../roms/n64/Magical Tetris Challenge (USA).z64"
rm "../roms/n64/Mahjong 64 (Japan).z64"
rm "../roms/n64/Mahjong Hourouki Classic (Japan).z64"
rm "../roms/n64/Mahjong Master (Japan).z64"
rm "../roms/n64/Major League Baseball featuring Ken Griffey Jr. (USA).z64"
rm "../roms/n64/Mario Golf (USA).z64"
rm "../roms/n64/Mario Kart 64 (USA).z64"
rm "../roms/n64/Mario no Photopie (Japan).z64"
rm "../roms/n64/Mario Party 2 (USA).z64"
rm "../roms/n64/Mario Party 3 (USA).z64"
rm "../roms/n64/Mario Party (USA).z64"
rm "../roms/n64/Mario Tennis (USA).z64"
rm "../roms/n64/Mega Man 64 (USA).z64"
rm "../roms/n64/Mia Hamm Soccer 64 (USA) (En,Es).z64"
rm "../roms/n64/Mickey's Speedway USA (USA).z64"
rm "../roms/n64/Micro Machines 64 Turbo (USA).z64"
rm "../roms/n64/Midway's Greatest Arcade Hits - Volume 1 (USA).z64"
rm "../roms/n64/Mike Piazza's Strike Zone (USA).z64"
rm "../roms/n64/Milo's Astro Lanes (USA).z64"
rm "../roms/n64/Mini Racers (USA) (Ja) (Proto).z64"
rm "../roms/n64/Mischief Makers (USA) (Rev 1).z64"
rm "../roms/n64/Mission - Impossible (USA).z64"
rm "../roms/n64/Monaco Grand Prix (USA).z64"
rm "../roms/n64/Monopoly (USA).z64"
rm "../roms/n64/Monster Truck Madness 64 (USA).z64"
rm "../roms/n64/Morita Shougi 64 (Japan).z64"
rm "../roms/n64/Mortal Kombat 4 (USA).z64"
rm "../roms/n64/Mortal Kombat Mythologies - Sub-Zero (USA).z64"
rm "../roms/n64/Mortal Kombat Trilogy (USA) (Rev 2).z64"
rm "../roms/n64/MRC - Multi-Racing Championship (USA).z64"
rm "../roms/n64/Ms. Pac-Man - Maze Madness (USA).z64"
rm "../roms/n64/Mystical Ninja Starring Goemon (USA).z64"
rm "../roms/n64/Nagano Winter Olympics '98 (USA).z64"
rm "../roms/n64/Namco Museum 64 (USA).z64"
rm "../roms/n64/NASCAR 2000 (USA).z64"
rm "../roms/n64/NASCAR 99 (USA).z64"
rm "../roms/n64/NBA Courtside 2 featuring Kobe Bryant (USA).z64"
rm "../roms/n64/NBA Hangtime (USA).z64"
rm "../roms/n64/NBA in the Zone 2000 (USA).z64"
rm "../roms/n64/NBA in the Zone 2 (Japan).zip"
rm "../roms/n64/NBA in the Zone '98 (USA).z64"
rm "../roms/n64/NBA in the Zone '99 (USA).z64"
rm "../roms/n64/NBA Jam 2000 (USA).z64"
rm "../roms/n64/NBA Jam 99 (USA).z64"
rm "../roms/n64/NBA Live 2000 (USA) (En,Fr,De,Es).z64"
rm "../roms/n64/NBA Live 99 (USA) (En,Fr,De,Es,It).z64"
rm "../roms/n64/NBA Pro 98 (Europe).zip"
rm "../roms/n64/NBA Showtime - NBA on NBC (USA).z64"
rm "../roms/n64/Neon Genesis Evangelion (Japan).z64"
rm "../roms/n64/NFL Blitz 2000 (USA) (Rev 1).z64"
rm "../roms/n64/NFL Blitz 2001 (USA).z64"
rm "../roms/n64/NFL Blitz - Special Edition (USA).z64"
rm "../roms/n64/NFL Blitz (USA).z64"
rm "../roms/n64/NFL QB Club 2001 (USA).z64"
rm "../roms/n64/NFL Quarterback Club 2000 (USA).z64"
rm "../roms/n64/NFL Quarterback Club 98 (USA).z64"
rm "../roms/n64/NFL Quarterback Club 99 (USA).z64"
rm "../roms/n64/NHL 99 (USA).z64"
rm "../roms/n64/NHL Blades of Steel '99 (USA).z64"
rm "../roms/n64/NHL Breakaway 98 (USA).z64"
rm "../roms/n64/NHL Breakaway 99 (USA).z64"
rm "../roms/n64/Nightmare Creatures (USA).z64"
rm "../roms/n64/Nintama Rantarou 64 Game Gallery (Japan).z64"
rm "../roms/n64/Nuclear Strike 64 (USA).z64"
rm "../roms/n64/Nushi Zuri 64 (Japan) (Rev 1).z64"
rm "../roms/n64/Nushi Zuri 64 - Shiokaze ni Notte (Japan).z64"
rm "../roms/n64/O.D.T. (USA) (En,Fr,Es) (Proto).z64"
rm "../roms/n64/Off Road Challenge (USA).z64"
rm "../roms/n64/Ogre Battle 64 - Person of Lordly Caliber (USA) (Rev 1).z64"
rm "../roms/n64/Olympic Hockey 98 (USA).z64"
rm "../roms/n64/Onegai Monsters (Japan).z64"
rm "../roms/n64/Operation WinBack (Europe) (En,Fr,De,Es,It).zip"
rm "../roms/n64/Pachinko 365 Nichi (Japan).z64"
rm "../roms/n64/Paperboy (USA).z64"
rm "../roms/n64/Paper Mario (USA).z64"
rm "../roms/n64/Parlor! Pro 64 - Pachinko Jikki Simulation Game (Japan).z64"
rm "../roms/n64/PD Ultraman Battle Collection 64 (Japan).z64"
rm "../roms/n64/Penny Racers (USA).z64"
rm "../roms/n64/Perfect Dark (USA) (Rev 1).z64"
rm "../roms/n64/PGA European Tour (USA).z64"
rm "../roms/n64/Pilotwings 64 (USA).z64"
rm "../roms/n64/Pokemon Puzzle League (USA).z64"
rm "../roms/n64/Pokemon Snap (USA).z64"
rm "../roms/n64/Pokemon Stadium 2 (USA).z64"
rm "../roms/n64/Pokemon Stadium (USA) (Rev 2).z64"
rm "../roms/n64/Polaris SnoCross (USA).z64"
rm "../roms/n64/Power League 64 (Japan).z64"
rm "../roms/n64/Power Rangers - Lightspeed Rescue (USA).z64"
rm "../roms/n64/Premier Manager 64 (Europe).z64"
rm "../roms/n64/Pro Mahjong Kiwame 64 (Japan) (Rev 1).z64"
rm "../roms/n64/Pro Mahjong Tsuwamono 64 - Jansou Battle ni Chousen (Japan).z64"
rm "../roms/n64/Puyo Puyoon Party (Japan).z64"
rm "../roms/n64/Puyo Puyo Sun 64 (Japan).z64"
rm "../roms/n64/Quake II (USA).z64"
rm "../roms/n64/Quake (USA).z64"
rm "../roms/n64/Quest 64 (USA).z64"
rm "../roms/n64/Rakugakids (Europe).z64"
rm "../roms/n64/Rally '99 (Japan).zip"
rm "../roms/n64/Rally Challenge 2000 (USA).z64"
rm "../roms/n64/Rampage 2 - Universal Tour (USA).z64"
rm "../roms/n64/Rampage - World Tour (USA).z64"
rm "../roms/n64/Rat Attack! (USA) (En,Fr,De,Es,It,Nl).z64"
rm "../roms/n64/Rayman 2 - The Great Escape (USA) (En,Fr,De,Es,It).z64"
rm "../roms/n64/Razor Freestyle Scooter (USA).z64"
rm "../roms/n64/Ready 2 Rumble Boxing - Round 2 (USA).z64"
rm "../roms/n64/Ready 2 Rumble Boxing (USA).z64"
rm "../roms/n64/Resident Evil 2 (USA) (Rev 1).z64"
rm "../roms/n64/Re-Volt (USA).z64"
rm "../roms/n64/Road Rash 64 (USA).z64"
rm "../roms/n64/Roadsters (USA) (En,Fr,Es).z64"
rm "../roms/n64/Robotech - Crystal Dreams (USA) (Proto 2).z64"
rm "../roms/n64/Robot Poncots 64 - 7tsu no Umi no Caramel (Japan).z64"
rm "../roms/n64/Robotron 64 (USA).z64"
rm "../roms/n64/Rocket - Robot on Wheels (USA).z64"
rm "../roms/n64/Rockman Dash - Hagane no Boukenshin (Japan).zip"
rm "../roms/n64/RR64 - Ridge Racer 64 (USA).z64"
rm "../roms/n64/Rugrats in Paris - The Movie (USA).z64"
rm "../roms/n64/Rugrats - Scavenger Hunt (USA).z64"
rm "../roms/n64/Rush 2 - Extreme Racing USA (USA).z64"
rm "../roms/n64/Saikyou Habu Shougi (Japan).z64"
rm "../roms/n64/San Francisco Rush 2049 (USA).z64"
rm "../roms/n64/San Francisco Rush - Extreme Racing (USA) (En,Fr,De) (Rev 1).z64"
rm "../roms/n64/S.C.A.R.S. (USA).z64"
rm "../roms/n64/Scooby-Doo! - Classic Creep Capers (USA) (Rev 1).z64"
rm "../roms/n64/SD Hiryuu no Ken Densetsu (Japan).z64"
rm "../roms/n64/Sesame Street - Elmo's Letter Adventure (USA).z64"
rm "../roms/n64/Sesame Street - Elmo's Number Journey (USA).z64"
rm "../roms/n64/Shadowgate 64 - Trials of the Four Towers (USA) (En,Es).z64"
rm "../roms/n64/Shadow Man (USA).z64"
rm "../roms/n64/Shin Nihon Pro Wrestling Toukon Road 2 - The Next Generation (Japan).z64"
rm "../roms/n64/Shin Nihon Pro Wrestling Toukon Road - Brave Spirits (Japan).z64"
rm "../roms/n64/SimCity 2000 (Japan).z64"
rm "../roms/n64/Snowboard Kids 2 (USA).z64"
rm "../roms/n64/Snowboard Kids (USA).z64"
rm "../roms/n64/Snow Speeder (Japan).zip"
rm "../roms/n64/Sonic Wings Assault (Japan).zip"
rm "../roms/n64/South Park - Chef's Luv Shack (USA).z64"
rm "../roms/n64/South Park Rally (USA).z64"
rm "../roms/n64/South Park (USA).z64"
rm "../roms/n64/Space Dynamites (Japan).zip"
rm "../roms/n64/Space Invaders (USA).z64"
rm "../roms/n64/SpaceStation Silicon Valley (USA) (Rev 1).z64"
rm "../roms/n64/Spider-Man (USA).z64"
rm "../roms/n64/StarCraft 64 (USA).z64"
rm "../roms/n64/Star Fox 64 (USA) (Rev 1).z64"
rm "../roms/n64/Starshot - Space Circus Fever (USA) (En,Fr,Es).z64"
rm "../roms/n64/Star Soldier - Vanishing Earth (USA).z64"
rm "../roms/n64/Star Twins (Japan).zip"
rm "../roms/n64/Star Wars Episode I - Battle for Naboo (USA).z64"
rm "../roms/n64/Star Wars Episode I - Racer (USA).z64"
rm "../roms/n64/Star Wars - Rogue Squadron (USA) (Rev 1).z64"
rm "../roms/n64/Star Wars - Shadows of the Empire (USA) (Rev 2).z64"
rm "../roms/n64/Stunt Racer 64 (USA).z64"
rm "../roms/n64/Super B-Daman - Battle Phoenix 64 (Japan).z64"
rm "../roms/n64/Super Bowling (USA).z64"
rm "../roms/n64/Supercross 2000 (USA).z64"
rm "../roms/n64/Superman - The New Superman Aventures (USA) (En,Fr,Es).z64"
rm "../roms/n64/Super Mario 64 (USA).z64"
rm "../roms/n64/Super Robot Spirits (Japan).z64"
rm "../roms/n64/Super Robot Taisen 64 (Japan).z64"
rm "../roms/n64/Super Smash Bros. (USA).z64"
rm "../roms/n64/Susume! Taisen Puzzle Dama - Toukon! Marutama Chou (Japan).z64"
rm "../roms/n64/Sydney 2000 (USA) (Proto).z64"
rm "../roms/n64/Tamiya Racing 64 (USA) (Proto).zip"
rm "../roms/n64/Tarzan (USA).z64"
rm "../roms/n64/Taz Express (USA) (Proto) (2000-05-15).z64"
rm "../roms/n64/Telefoot Soccer 2000 (France).zip"
rm "../roms/n64/Tetris 64 (Japan) (En).z64"
rm "../roms/n64/Tetrisphere (USA).z64"
rm "../roms/n64/The Legend of Zelda - Majora's Mask (USA).z64"
rm "../roms/n64/The Legend of Zelda - Ocarina of Time - Master Quest (USA) (GameCube).z64"
rm "../roms/n64/The Legend of Zelda - Ocarina of Time (USA) (Rev 2).z64"
rm "../roms/n64/The New Tetris (USA).z64"
rm "../roms/n64/The Powerpuff Girls - Chemical X-Traction (USA).z64"
rm "../roms/n64/Tigger's Honey Hunt (USA).z64"
rm "../roms/n64/Tom and Jerry in Fists of Furry (USA).z64"
rm "../roms/n64/Tom Clancy's Rainbow Six (USA).z64"
rm "../roms/n64/Tommy Thunder (USA) (Proto).z64"
rm "../roms/n64/Tonic Trouble (USA) (Rev 1).z64"
rm "../roms/n64/Tony Hawk's Pro Skater 2 (USA).z64"
rm "../roms/n64/Tony Hawk's Pro Skater 3 (USA).z64"
rm "../roms/n64/Tony Hawk's Pro Skater (USA) (Rev 1).z64"
rm "../roms/n64/Toon Panic (Japan) (Proto).z64"
rm "../roms/n64/Top Gear Hyper-Bike (USA).z64"
rm "../roms/n64/Top Gear Overdrive (USA).z64"
rm "../roms/n64/Top Gear Rally 2 (USA).z64"
rm "../roms/n64/Top Gear Rally (USA).z64"
rm "../roms/n64/Toy Story 2 - Buzz Lightyear to the Rescue! (USA) (Rev 1).z64"
rm "../roms/n64/Transformers - Beast Wars Transmetals (USA).z64"
rm "../roms/n64/Triple Play 2000 (USA).z64"
rm "../roms/n64/Tsumi to Batsu - Hoshi no Keishousha (Japan).z64"
rm "../roms/n64/Turok 2 - Seeds of Evil (USA) (Rev 1).z64"
rm "../roms/n64/Turok 3 - Shadow of Oblivion (USA).z64"
rm "../roms/n64/Turok - Dinosaur Hunter (USA) (Rev 2).z64"
rm "../roms/n64/Turok - Rage Wars (USA) (Rev 1).z64"
rm "../roms/n64/Twisted Edge - Extreme Snowboarding (USA).z64"
rm "../roms/n64/Utchan Nanchan no Hono no Challenger - Denryuu Ira Ira Bou (Japan).z64"
rm "../roms/n64/Vigilante 8 - 2nd Offense (USA).z64"
rm "../roms/n64/Vigilante 8 (USA).z64"
rm "../roms/n64/Violence Killer - Turok New Generation (Japan).zip"
rm "../roms/n64/Virtual Chess 64 (USA) (En,Fr,Es).z64"
rm "../roms/n64/Virtual Pool 64 (USA).z64"
rm "../roms/n64/Virtual Pro Wrestling 2 - Oudou Keishou (Japan).z64"
rm "../roms/n64/Virtual Pro Wrestling 64 (Japan).z64"
rm "../roms/n64/V-Rally Edition 99 (USA).z64"
rm "../roms/n64/Waialae Country Club - True Golf Classics (USA) (Rev 1).z64"
rm "../roms/n64/War Gods (USA).z64"
rm "../roms/n64/Wave Race 64 - Kawasaki Jet Ski (USA) (Rev 1).z64"
rm "../roms/n64/Wayne Gretzky's 3D Hockey '98 (USA).n64"
rm "../roms/n64/Wayne Gretzky's 3D Hockey (USA) (Rev 1).z64"
rm "../roms/n64/WCW Backstage Assault (USA).z64"
rm "../roms/n64/WCW Mayhem (USA).z64"
rm "../roms/n64/WCW Nitro (USA).z64"
rm "../roms/n64/WCW-nWo Revenge (USA).z64"
rm "../roms/n64/WCW vs. nWo - World Tour (USA) (Rev 1).z64"
rm "../roms/n64/Wetrix (USA) (En,Fr,De,Es,It,Nl).z64"
rm "../roms/n64/Wheel of Fortune (USA).z64"
rm "../roms/n64/Wildwaters (USA) (Proto).z64"
rm "../roms/n64/WinBack - Covert Operations (USA).z64"
rm "../roms/n64/Wipeout 64 (USA).z64"
rm "../roms/n64/Wonder Project J2 - Koruro no Mori no Jozet (Japan).z64"
rm "../roms/n64/World Cup 98 (USA) (En,Fr,De,Es,It,Nl,Sv,Da).z64"
rm "../roms/n64/World Driver Championship (USA).z64"
rm "../roms/n64/Worms Armageddon (USA) (En,Fr,Es).z64"
rm "../roms/n64/WWF Attitude (USA).z64"
rm "../roms/n64/WWF No Mercy (USA) (Rev 1).z64"
rm "../roms/n64/WWF War Zone (USA).z64"
rm "../roms/n64/WWF WrestleMania 2000 (USA).z64"
rm "../roms/n64/Xena - Warrior Princess - The Talisman of Fate (USA).z64"
rm "../roms/n64/Yakouchuu II - Satsujin Kouro (Japan).z64"
rm "../roms/n64/Yoshi's Story (USA) (En,Ja).z64"
rm "../roms/n64/Zool - Majuu Tsukai Densetsu (Japan).z64"
echo
echo "Getting games"
echo
wget -P ../roms/n64/ "${RUTA}007 - The World Is Not Enough (USA).z64"
wget -P ../roms/n64/ "${RUTA}1080 TenEighty Snowboarding (Japan, USA) (En,Ja).z64"
wget -P ../roms/n64/ "${RUTA}40 Winks (Europe) (En,Es,It) (Proto) (1999-10-07).z64"
wget -P ../roms/n64/ "${RUTA}64 de Hakken!! Tamagotchi - Minna de Tamagotchi World (Japan).z64"
wget -P ../roms/n64/ "${RUTA}64 Hanafuda - Tenshi no Yakusoku (Japan).z64"
wget -P ../roms/n64/ "${RUTA}64 Oozumou 2 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}64 Oozumou (Japan).z64"
wget -P ../roms/n64/ "${RUTA}64 Trump Collection - Alice no Wakuwaku Trump World (Japan).z64"
wget -P ../roms/n64/ "${RUTA}A Bug's Life (USA).z64"
wget -P ../roms/n64/ "${RUTA}AeroFighters Assault (USA).z64"
wget -P ../roms/n64/ "${RUTA}AeroGauge (USA).z64"
wget -P ../roms/n64/ "${RUTA}Aidyn Chronicles - The First Mage (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Airboarder 64 (Europe).z64"
wget -P ../roms/n64/ "${RUTA}AI Shougi 3 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}All-Star Baseball 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}All-Star Baseball 2001 (USA).z64"
wget -P ../roms/n64/ "${RUTA}All-Star Baseball 99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}All Star Tennis 99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Armorines - Project S.W.A.R.M. (USA).z64"
wget -P ../roms/n64/ "${RUTA}Army Men - Air Combat (USA).z64"
wget -P ../roms/n64/ "${RUTA}Army Men - Sarge's Heroes 2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Army Men - Sarge's Heroes (USA).z64"
wget -P ../roms/n64/ "${RUTA}Asteroids Hyper 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Automobili Lamborghini (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bakuretsu Muteki Bangaioh (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Bakushou Jinsei 64 - Mezase! Resort Ou (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Banjo-Kazooie (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Banjo-Tooie (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bassmasters 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bass Rush - ECOGEAR PowerWorm Championship (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Batman Beyond - Return of the Joker (USA).z64"
wget -P ../roms/n64/ "${RUTA}BattleTanx - Global Assault (USA).z64"
wget -P ../roms/n64/ "${RUTA}BattleTanx (USA).z64"
wget -P ../roms/n64/ "${RUTA}Battlezone - Rise of the Black Dogs (USA).z64"
wget -P ../roms/n64/ "${RUTA}Beetle Adventure Racing! (USA) (En,Fr,De).z64"
wget -P ../roms/n64/ "${RUTA}Big Mountain 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bio F.R.E.A.K.S. (USA).z64"
wget -P ../roms/n64/ "${RUTA}Blast Corps (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Blues Brothers 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Body Harvest (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bomberman 64 Classic(Japan).z64"
wget -P ../roms/n64/ "${RUTA}Bomberman 64 - The Second Attack! (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bomberman 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bomberman Hero (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bottom of the 9th (USA).z64"
wget -P ../roms/n64/ "${RUTA}Brunswick Circuit Pro Bowling (USA).z64"
wget -P ../roms/n64/ "${RUTA}Buck Bumble (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bust-A-Move 2 - Arcade Edition (USA).z64"
wget -P ../roms/n64/ "${RUTA}Bust-A-Move '99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}California Speed (USA).z64"
wget -P ../roms/n64/ "${RUTA}Carmageddon 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Castlevania - Legacy of Darkness (USA).z64"
wget -P ../roms/n64/ "${RUTA}Castlevania (USA) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}Centre Court Tennis (Europe).z64"
wget -P ../roms/n64/ "${RUTA}Chameleon Twist 2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Chameleon Twist (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Charlie Blast's Territory (USA).z64"
wget -P ../roms/n64/ "${RUTA}Chopper Attack (USA).z64"
wget -P ../roms/n64/ "${RUTA}Choro Q 64 2 - Hacha Mecha Grand Prix Race (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Chou Kuukan Nighter Pro Yakyuu King 2 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Chou Kuukan Nighter Pro Yakyuu King (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Clay Fighter 63 1-3 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Clay Fighter - Sculptor's Cut (USA).z64"
wget -P ../roms/n64/ "${RUTA}Command & Conquer (USA).z64"
wget -P ../roms/n64/ "${RUTA}Conker's Bad Fur Day (USA).z64"
wget -P ../roms/n64/ "${RUTA}Cruis'n Exotica (USA).z64"
wget -P ../roms/n64/ "${RUTA}Cruis'n USA (USA) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}Cruis'n World (USA).z64"
wget -P ../roms/n64/ "${RUTA}Custom Robo (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Custom Robo V2 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}CyberTiger (USA).z64"
wget -P ../roms/n64/ "${RUTA}Dance Dance Revolution - Disney Dancing Museum (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Dark Rift (USA).z64"
wget -P ../roms/n64/ "${RUTA}Deadly Arts (USA).z64"
wget -P ../roms/n64/ "${RUTA}Densha de Go! 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Derby Stallion 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Destruction Derby 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Dezaemon 3D (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Diddy Kong Racing (USA) (En,Fr) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Die Hard 64 (USA) (Proto) (Level 1).z64"
wget -P ../roms/n64/ "${RUTA}Donald Duck - Goin' Quackers (USA) (En,Fr,De,Es,It).z64"
wget -P ../roms/n64/ "${RUTA}Donkey Kong 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Doom 64 (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Doraemon 2 - Nobita to Hikari no Shinden (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Doraemon 3 - Nobita no Machi SOS! (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Doraemon - Nobita to 3tsu no Seireiseki (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Doubutsu no Mori (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Dragon Sword 64 (USA) (Proto) (1999-08-25).z64"
wget -P ../roms/n64/ "${RUTA}Dr. Mario 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Dual Heroes (USA).z64"
wget -P ../roms/n64/ "${RUTA}Duck Dodgers Starring Daffy Duck (USA) (En,Fr,Es).z64"
wget -P ../roms/n64/ "${RUTA}Duke Nukem 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Duke Nukem - Zero Hour (USA).z64"
wget -P ../roms/n64/ "${RUTA}Earthworm Jim 3D (USA).z64"
wget -P ../roms/n64/ "${RUTA}ECW Hardcore Revolution (USA).z64"
wget -P ../roms/n64/ "${RUTA}Eikou no Saint Andrews (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Excitebike 64 (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Extreme-G (USA).z64"
wget -P ../roms/n64/ "${RUTA}Extreme-G XG2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}F1 Pole Position 64 (USA) (En,Fr,De).z64"
wget -P ../roms/n64/ "${RUTA}F1 Racing Championship (Europe) (En,Fr,De,Es,It).z64"
wget -P ../roms/n64/ "${RUTA}F-1 World Grand Prix II (Europe) (En,Fr,De,Es).z64"
wget -P ../roms/n64/ "${RUTA}F-1 World Grand Prix (USA).z64"
wget -P ../roms/n64/ "${RUTA}Famista 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}FIFA 99 (USA) (En,Fr,De,Es,It,Nl,Pt,Sv).z64"
wget -P ../roms/n64/ "${RUTA}FIFA - Road to World Cup 98 (USA) (En,Fr,De,Es,It,Nl,Sv).z64"
wget -P ../roms/n64/ "${RUTA}FIFA Soccer 64 (USA) (En,Fr,De).z64"
wget -P ../roms/n64/ "${RUTA}Fighter Destiny 2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Fighters Destiny (USA).z64"
wget -P ../roms/n64/ "${RUTA}Fighting Force 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Flying Dragon (USA).z64"
wget -P ../roms/n64/ "${RUTA}Forsaken 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Fox Sports College Hoops '99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Frogger 2 (USA) (Proto 2).z64"
wget -P ../roms/n64/ "${RUTA}Fushigi no Dungeon - Fuurai no Shiren 2 - Oni Shuurai! Shiren Jou! (Japan).z64"
wget -P ../roms/n64/ "${RUTA}F-Zero X (USA).z64"
wget -P ../roms/n64/ "${RUTA}gamelist.xml"
wget -P ../roms/n64/ "${RUTA}G.A.S.P!! Fighters' NEXTream (Japan).zip"
wget -P ../roms/n64/ "${RUTA}Gauntlet Legends (USA).z64"
wget -P ../roms/n64/ "${RUTA}Getter Love!! - Cho Renai Party Game Tanjou (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Gex 3 - Deep Cover Gecko (USA).z64"
wget -P ../roms/n64/ "${RUTA}Gex 64 - Enter the Gecko (USA).z64"
wget -P ../roms/n64/ "${RUTA}Glover 2 (USA) (Proto 2).z64"
wget -P ../roms/n64/ "${RUTA}Glover (USA).z64"
wget -P ../roms/n64/ "${RUTA}Goemon - Mononoke Sugoroku (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Goemon's Great Adventure (USA).z64"
wget -P ../roms/n64/ "${RUTA}GoldenEye 007 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Golden Nugget 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}GT 64 - Championship Edition (USA).z64"
wget -P ../roms/n64/ "${RUTA}Hamster Monogatari 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Harukanaru Augusta - Masters '98 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Harvest Moon 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Heiwa Pachinko World 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Hercules - The Legendary Journeys (USA).z64"
wget -P ../roms/n64/ "${RUTA}Hexen (USA).z64"
wget -P ../roms/n64/ "${RUTA}Hey You, Pikachu! (USA).z64"
wget -P ../roms/n64/ "${RUTA}Hot Wheels - Turbo Racing (USA).z64"
wget -P ../roms/n64/ "${RUTA}HSV Adventure Racing! (Australia).zip"
wget -P ../roms/n64/ "${RUTA}Hybrid Heaven (USA).z64"
wget -P ../roms/n64/ "${RUTA}Hydro Thunder (USA).z64"
wget -P ../roms/n64/ "${RUTA}Ide Yosuke no Mahjong Juku (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Iggy's Reckin' Balls (USA).z64"
wget -P ../roms/n64/ "${RUTA}Indiana Jones and the Infernal Machine (USA).z64"
wget -P ../roms/n64/ "${RUTA}Indy Racing 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}In-Fisherman - Bass Hunter 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}International Superstar Soccer 2000 (USA) (En,Es) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}International Superstar Soccer 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}International Superstar Soccer '98 (USA).z64"
wget -P ../roms/n64/ "${RUTA}International Track & Field 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Itoi Shigesato no Bass Tsuri No. 1 Kettei Ban! (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Jangou Simulation Mahjong Dou 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Jeopardy! (USA).z64"
wget -P ../roms/n64/ "${RUTA}Jeremy McGrath Supercross 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Jet Force Gemini (USA).z64"
wget -P ../roms/n64/ "${RUTA}Jikkyou G1 Stable (Japan) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Jikkyou J.League Perfect Striker (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Jikkyou Powerful Pro Yakyuu 2000 (Japan) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Jikkyou Powerful Pro Yakyuu 4 (Japan) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Jikkyou Powerful Pro Yakyuu 5 (Japan) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}Jikkyou Powerful Pro Yakyuu 6 (Japan) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}Jikkyou Powerful Pro Yakyuu - Basic Ban 2001 (Japan) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Jinsei Game 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}J.League Dynamite Soccer 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}J.League Eleven Beat 1997 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}J.League Live 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}J.League Tactics Soccer (Japan) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}John Romero's Daikatana (USA).z64"
wget -P ../roms/n64/ "${RUTA}Ken Griffey Jr.'s Slugfest (USA).z64"
wget -P ../roms/n64/ "${RUTA}Killer Instinct Gold (USA) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}King Hill 64 - Extreme Snowboarding (Japan).zip"
wget -P ../roms/n64/ "${RUTA}Kiratto Kaiketsu! 64 Tanteidan (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Kirby 64 - The Crystal Shards (USA).z64"
wget -P ../roms/n64/ "${RUTA}Knife Edge - Nose Gunner (USA).z64"
wget -P ../roms/n64/ "${RUTA}Knockout Kings 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Kobe Bryant in NBA Courtside (USA).z64"
wget -P ../roms/n64/ "${RUTA}Last Legion UX (Japan).z64"
wget -P ../roms/n64/ "${RUTA}LEGO Racers (USA) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).z64"
wget -P ../roms/n64/ "${RUTA}Lode Runner 3-D (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mace - The Dark Age (USA).z64"
wget -P ../roms/n64/ "${RUTA}Madden Football 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Madden NFL 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Madden NFL 2001 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Madden NFL 2002 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Madden NFL 99 (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Magical Tetris Challenge (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mahjong 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Mahjong Hourouki Classic (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Mahjong Master (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Major League Baseball featuring Ken Griffey Jr. (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mario Golf (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mario Kart 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mario no Photopie (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Mario Party 2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mario Party 3 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mario Party (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mario Tennis (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mega Man 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mia Hamm Soccer 64 (USA) (En,Es).z64"
wget -P ../roms/n64/ "${RUTA}Mickey's Speedway USA (USA).z64"
wget -P ../roms/n64/ "${RUTA}Micro Machines 64 Turbo (USA).z64"
wget -P ../roms/n64/ "${RUTA}Midway's Greatest Arcade Hits - Volume 1 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mike Piazza's Strike Zone (USA).z64"
wget -P ../roms/n64/ "${RUTA}Milo's Astro Lanes (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mini Racers (USA) (Ja) (Proto).z64"
wget -P ../roms/n64/ "${RUTA}Mischief Makers (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Mission - Impossible (USA).z64"
wget -P ../roms/n64/ "${RUTA}Monaco Grand Prix (USA).z64"
wget -P ../roms/n64/ "${RUTA}Monopoly (USA).z64"
wget -P ../roms/n64/ "${RUTA}Monster Truck Madness 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Morita Shougi 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Mortal Kombat 4 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mortal Kombat Mythologies - Sub-Zero (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mortal Kombat Trilogy (USA) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}MRC - Multi-Racing Championship (USA).z64"
wget -P ../roms/n64/ "${RUTA}Ms. Pac-Man - Maze Madness (USA).z64"
wget -P ../roms/n64/ "${RUTA}Mystical Ninja Starring Goemon (USA).z64"
wget -P ../roms/n64/ "${RUTA}Nagano Winter Olympics '98 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Namco Museum 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NASCAR 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NASCAR 99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NBA Courtside 2 featuring Kobe Bryant (USA).z64"
wget -P ../roms/n64/ "${RUTA}NBA Hangtime (USA).z64"
wget -P ../roms/n64/ "${RUTA}NBA in the Zone 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NBA in the Zone 2 (Japan).zip"
wget -P ../roms/n64/ "${RUTA}NBA in the Zone '98 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NBA in the Zone '99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NBA Jam 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NBA Jam 99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NBA Live 2000 (USA) (En,Fr,De,Es).z64"
wget -P ../roms/n64/ "${RUTA}NBA Live 99 (USA) (En,Fr,De,Es,It).z64"
wget -P ../roms/n64/ "${RUTA}NBA Pro 98 (Europe).zip"
wget -P ../roms/n64/ "${RUTA}NBA Showtime - NBA on NBC (USA).z64"
wget -P ../roms/n64/ "${RUTA}Neon Genesis Evangelion (Japan).z64"
wget -P ../roms/n64/ "${RUTA}NFL Blitz 2000 (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}NFL Blitz 2001 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NFL Blitz - Special Edition (USA).z64"
wget -P ../roms/n64/ "${RUTA}NFL Blitz (USA).z64"
wget -P ../roms/n64/ "${RUTA}NFL QB Club 2001 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NFL Quarterback Club 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NFL Quarterback Club 98 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NFL Quarterback Club 99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NHL 99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NHL Blades of Steel '99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NHL Breakaway 98 (USA).z64"
wget -P ../roms/n64/ "${RUTA}NHL Breakaway 99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Nightmare Creatures (USA).z64"
wget -P ../roms/n64/ "${RUTA}Nintama Rantarou 64 Game Gallery (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Nuclear Strike 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Nushi Zuri 64 (Japan) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Nushi Zuri 64 - Shiokaze ni Notte (Japan).z64"
wget -P ../roms/n64/ "${RUTA}O.D.T. (USA) (En,Fr,Es) (Proto).z64"
wget -P ../roms/n64/ "${RUTA}Off Road Challenge (USA).z64"
wget -P ../roms/n64/ "${RUTA}Ogre Battle 64 - Person of Lordly Caliber (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Olympic Hockey 98 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Onegai Monsters (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Operation WinBack (Europe) (En,Fr,De,Es,It).zip"
wget -P ../roms/n64/ "${RUTA}Pachinko 365 Nichi (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Paperboy (USA).z64"
wget -P ../roms/n64/ "${RUTA}Paper Mario (USA).z64"
wget -P ../roms/n64/ "${RUTA}Parlor! Pro 64 - Pachinko Jikki Simulation Game (Japan).z64"
wget -P ../roms/n64/ "${RUTA}PD Ultraman Battle Collection 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Penny Racers (USA).z64"
wget -P ../roms/n64/ "${RUTA}Perfect Dark (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}PGA European Tour (USA).z64"
wget -P ../roms/n64/ "${RUTA}Pilotwings 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Pokemon Puzzle League (USA).z64"
wget -P ../roms/n64/ "${RUTA}Pokemon Snap (USA).z64"
wget -P ../roms/n64/ "${RUTA}Pokemon Stadium 2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Pokemon Stadium (USA) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}Polaris SnoCross (USA).z64"
wget -P ../roms/n64/ "${RUTA}Power League 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Power Rangers - Lightspeed Rescue (USA).z64"
wget -P ../roms/n64/ "${RUTA}Premier Manager 64 (Europe).z64"
wget -P ../roms/n64/ "${RUTA}Pro Mahjong Kiwame 64 (Japan) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Pro Mahjong Tsuwamono 64 - Jansou Battle ni Chousen (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Puyo Puyoon Party (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Puyo Puyo Sun 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Quake II (USA).z64"
wget -P ../roms/n64/ "${RUTA}Quake (USA).z64"
wget -P ../roms/n64/ "${RUTA}Quest 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Rakugakids (Europe).z64"
wget -P ../roms/n64/ "${RUTA}Rally '99 (Japan).zip"
wget -P ../roms/n64/ "${RUTA}Rally Challenge 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Rampage 2 - Universal Tour (USA).z64"
wget -P ../roms/n64/ "${RUTA}Rampage - World Tour (USA).z64"
wget -P ../roms/n64/ "${RUTA}Rat Attack! (USA) (En,Fr,De,Es,It,Nl).z64"
wget -P ../roms/n64/ "${RUTA}Rayman 2 - The Great Escape (USA) (En,Fr,De,Es,It).z64"
wget -P ../roms/n64/ "${RUTA}Razor Freestyle Scooter (USA).z64"
wget -P ../roms/n64/ "${RUTA}Ready 2 Rumble Boxing - Round 2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Ready 2 Rumble Boxing (USA).z64"
wget -P ../roms/n64/ "${RUTA}Resident Evil 2 (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Re-Volt (USA).z64"
wget -P ../roms/n64/ "${RUTA}Road Rash 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Roadsters (USA) (En,Fr,Es).z64"
wget -P ../roms/n64/ "${RUTA}Robotech - Crystal Dreams (USA) (Proto 2).z64"
wget -P ../roms/n64/ "${RUTA}Robot Poncots 64 - 7tsu no Umi no Caramel (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Robotron 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Rocket - Robot on Wheels (USA).z64"
wget -P ../roms/n64/ "${RUTA}Rockman Dash - Hagane no Boukenshin (Japan).zip"
wget -P ../roms/n64/ "${RUTA}RR64 - Ridge Racer 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Rugrats in Paris - The Movie (USA).z64"
wget -P ../roms/n64/ "${RUTA}Rugrats - Scavenger Hunt (USA).z64"
wget -P ../roms/n64/ "${RUTA}Rush 2 - Extreme Racing USA (USA).z64"
wget -P ../roms/n64/ "${RUTA}Saikyou Habu Shougi (Japan).z64"
wget -P ../roms/n64/ "${RUTA}San Francisco Rush 2049 (USA).z64"
wget -P ../roms/n64/ "${RUTA}San Francisco Rush - Extreme Racing (USA) (En,Fr,De) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}S.C.A.R.S. (USA).z64"
wget -P ../roms/n64/ "${RUTA}Scooby-Doo! - Classic Creep Capers (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}SD Hiryuu no Ken Densetsu (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Sesame Street - Elmo's Letter Adventure (USA).z64"
wget -P ../roms/n64/ "${RUTA}Sesame Street - Elmo's Number Journey (USA).z64"
wget -P ../roms/n64/ "${RUTA}Shadowgate 64 - Trials of the Four Towers (USA) (En,Es).z64"
wget -P ../roms/n64/ "${RUTA}Shadow Man (USA).z64"
wget -P ../roms/n64/ "${RUTA}Shin Nihon Pro Wrestling Toukon Road 2 - The Next Generation (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Shin Nihon Pro Wrestling Toukon Road - Brave Spirits (Japan).z64"
wget -P ../roms/n64/ "${RUTA}SimCity 2000 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Snowboard Kids 2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Snowboard Kids (USA).z64"
wget -P ../roms/n64/ "${RUTA}Snow Speeder (Japan).zip"
wget -P ../roms/n64/ "${RUTA}Sonic Wings Assault (Japan).zip"
wget -P ../roms/n64/ "${RUTA}South Park - Chef's Luv Shack (USA).z64"
wget -P ../roms/n64/ "${RUTA}South Park Rally (USA).z64"
wget -P ../roms/n64/ "${RUTA}South Park (USA).z64"
wget -P ../roms/n64/ "${RUTA}Space Dynamites (Japan).zip"
wget -P ../roms/n64/ "${RUTA}Space Invaders (USA).z64"
wget -P ../roms/n64/ "${RUTA}SpaceStation Silicon Valley (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Spider-Man (USA).z64"
wget -P ../roms/n64/ "${RUTA}StarCraft 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Star Fox 64 (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Starshot - Space Circus Fever (USA) (En,Fr,Es).z64"
wget -P ../roms/n64/ "${RUTA}Star Soldier - Vanishing Earth (USA).z64"
wget -P ../roms/n64/ "${RUTA}Star Twins (Japan).zip"
wget -P ../roms/n64/ "${RUTA}Star Wars Episode I - Battle for Naboo (USA).z64"
wget -P ../roms/n64/ "${RUTA}Star Wars Episode I - Racer (USA).z64"
wget -P ../roms/n64/ "${RUTA}Star Wars - Rogue Squadron (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Star Wars - Shadows of the Empire (USA) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}Stunt Racer 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Super B-Daman - Battle Phoenix 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Super Bowling (USA).z64"
wget -P ../roms/n64/ "${RUTA}Supercross 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Superman - The New Superman Aventures (USA) (En,Fr,Es).z64"
wget -P ../roms/n64/ "${RUTA}Super Mario 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Super Robot Spirits (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Super Robot Taisen 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Super Smash Bros. (USA).z64"
wget -P ../roms/n64/ "${RUTA}Susume! Taisen Puzzle Dama - Toukon! Marutama Chou (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Sydney 2000 (USA) (Proto).z64"
wget -P ../roms/n64/ "${RUTA}Tamiya Racing 64 (USA) (Proto).zip"
wget -P ../roms/n64/ "${RUTA}Tarzan (USA).z64"
wget -P ../roms/n64/ "${RUTA}Taz Express (USA) (Proto) (2000-05-15).z64"
wget -P ../roms/n64/ "${RUTA}Telefoot Soccer 2000 (France).zip"
wget -P ../roms/n64/ "${RUTA}Tetris 64 (Japan) (En).z64"
wget -P ../roms/n64/ "${RUTA}Tetrisphere (USA).z64"
wget -P ../roms/n64/ "${RUTA}The Legend of Zelda - Majora's Mask (USA).z64"
wget -P ../roms/n64/ "${RUTA}The Legend of Zelda - Ocarina of Time - Master Quest (USA) (GameCube).z64"
wget -P ../roms/n64/ "${RUTA}The Legend of Zelda - Ocarina of Time (USA) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}The New Tetris (USA).z64"
wget -P ../roms/n64/ "${RUTA}The Powerpuff Girls - Chemical X-Traction (USA).z64"
wget -P ../roms/n64/ "${RUTA}Tigger's Honey Hunt (USA).z64"
wget -P ../roms/n64/ "${RUTA}Tom and Jerry in Fists of Furry (USA).z64"
wget -P ../roms/n64/ "${RUTA}Tom Clancy's Rainbow Six (USA).z64"
wget -P ../roms/n64/ "${RUTA}Tommy Thunder (USA) (Proto).z64"
wget -P ../roms/n64/ "${RUTA}Tonic Trouble (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Tony Hawk's Pro Skater 2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Tony Hawk's Pro Skater 3 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Tony Hawk's Pro Skater (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Toon Panic (Japan) (Proto).z64"
wget -P ../roms/n64/ "${RUTA}Top Gear Hyper-Bike (USA).z64"
wget -P ../roms/n64/ "${RUTA}Top Gear Overdrive (USA).z64"
wget -P ../roms/n64/ "${RUTA}Top Gear Rally 2 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Top Gear Rally (USA).z64"
wget -P ../roms/n64/ "${RUTA}Toy Story 2 - Buzz Lightyear to the Rescue! (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Transformers - Beast Wars Transmetals (USA).z64"
wget -P ../roms/n64/ "${RUTA}Triple Play 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Tsumi to Batsu - Hoshi no Keishousha (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Turok 2 - Seeds of Evil (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Turok 3 - Shadow of Oblivion (USA).z64"
wget -P ../roms/n64/ "${RUTA}Turok - Dinosaur Hunter (USA) (Rev 2).z64"
wget -P ../roms/n64/ "${RUTA}Turok - Rage Wars (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Twisted Edge - Extreme Snowboarding (USA).z64"
wget -P ../roms/n64/ "${RUTA}Utchan Nanchan no Hono no Challenger - Denryuu Ira Ira Bou (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Vigilante 8 - 2nd Offense (USA).z64"
wget -P ../roms/n64/ "${RUTA}Vigilante 8 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Violence Killer - Turok New Generation (Japan).zip"
wget -P ../roms/n64/ "${RUTA}Virtual Chess 64 (USA) (En,Fr,Es).z64"
wget -P ../roms/n64/ "${RUTA}Virtual Pool 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Virtual Pro Wrestling 2 - Oudou Keishou (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Virtual Pro Wrestling 64 (Japan).z64"
wget -P ../roms/n64/ "${RUTA}V-Rally Edition 99 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Waialae Country Club - True Golf Classics (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}War Gods (USA).z64"
wget -P ../roms/n64/ "${RUTA}Wave Race 64 - Kawasaki Jet Ski (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Wayne Gretzky's 3D Hockey '98 (USA).n64"
wget -P ../roms/n64/ "${RUTA}Wayne Gretzky's 3D Hockey (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}WCW Backstage Assault (USA).z64"
wget -P ../roms/n64/ "${RUTA}WCW Mayhem (USA).z64"
wget -P ../roms/n64/ "${RUTA}WCW Nitro (USA).z64"
wget -P ../roms/n64/ "${RUTA}WCW-nWo Revenge (USA).z64"
wget -P ../roms/n64/ "${RUTA}WCW vs. nWo - World Tour (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}Wetrix (USA) (En,Fr,De,Es,It,Nl).z64"
wget -P ../roms/n64/ "${RUTA}Wheel of Fortune (USA).z64"
wget -P ../roms/n64/ "${RUTA}Wildwaters (USA) (Proto).z64"
wget -P ../roms/n64/ "${RUTA}WinBack - Covert Operations (USA).z64"
wget -P ../roms/n64/ "${RUTA}Wipeout 64 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Wonder Project J2 - Koruro no Mori no Jozet (Japan).z64"
wget -P ../roms/n64/ "${RUTA}World Cup 98 (USA) (En,Fr,De,Es,It,Nl,Sv,Da).z64"
wget -P ../roms/n64/ "${RUTA}World Driver Championship (USA).z64"
wget -P ../roms/n64/ "${RUTA}Worms Armageddon (USA) (En,Fr,Es).z64"
wget -P ../roms/n64/ "${RUTA}WWF Attitude (USA).z64"
wget -P ../roms/n64/ "${RUTA}WWF No Mercy (USA) (Rev 1).z64"
wget -P ../roms/n64/ "${RUTA}WWF War Zone (USA).z64"
wget -P ../roms/n64/ "${RUTA}WWF WrestleMania 2000 (USA).z64"
wget -P ../roms/n64/ "${RUTA}Xena - Warrior Princess - The Talisman of Fate (USA).z64"
wget -P ../roms/n64/ "${RUTA}Yakouchuu II - Satsujin Kouro (Japan).z64"
wget -P ../roms/n64/ "${RUTA}Yoshi's Story (USA) (En,Ja).z64"
wget -P ../roms/n64/ "${RUTA}Zool - Majuu Tsukai Densetsu (Japan).z64"
echo
echo "Enjoy"
